version: "3.9"
services:
  database:
    image: postgres:17
    container_name: db-geo
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: lele_terbang
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: password
    networks:
      - reverse-geo
    volumes:
      - ${PWD}/tmp/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgre"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    container_name: redis-lele
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -h localhost -p 6379 ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - reverse-geo

networks:
  reverse-geo:
    driver: bridge

volumes:
  data-lele:
